name: publish-releases

permissions:
  contents: write # 允许创建或更新 Release

on:
  workflow_dispatch:
  push:
    paths:
      - 'package.json'

jobs:
  publish:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
      fail-fast: false

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set pnpm
        uses: pnpm/action-setup@v4
        with:
          version: latest

      - name: Set Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          registry-url: https://registry.npmjs.org
          cache: 'pnpm'

      - run: pnpm install
      - run: pnpm build

      - name: 发布 Electron 应用（${{ matrix.os }}）
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
      - run: npm run publish
